"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "../../../lib/supabase/client";

type Restaurant={id:number;name:string;city:string};
type Bid={id:number;restaurant_id:number;amount:number|string;payment_status:string;refund_status?:string|null;refund_amount?:number|string|null;razorpay_payment_id?:string|null;razorpay_order_id?:string|null;created_at:string};
const supabase=createClient();
const money=(n:number)=>`₹${Math.round(n).toLocaleString("en-IN")}`;

export default function RevenuePage(){
 const router=useRouter(); const [restaurants,setRestaurants]=useState<Restaurant[]>([]); const [bids,setBids]=useState<Bid[]>([]); const [range,setRange]=useState<7|30|90>(30); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/admin/login");return}const{data:admin}=await supabase.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle();if(!admin){router.replace("/admin/login");return}const[r,b]=await Promise.all([supabase.from("restaurants").select("id,name,city"),supabase.from("bids").select("id,restaurant_id,amount,payment_status,refund_status,refund_amount,razorpay_payment_id,razorpay_order_id,created_at").order("created_at",{ascending:false})]);const err=r.error||b.error;if(err)setError(err.message);setRestaurants((r.data||[])as Restaurant[]);setBids((b.data||[])as Bid[]);setLoading(false)})()},[router]);
 const cutoff=Date.now()-range*86400000;const recent=bids.filter(b=>new Date(b.created_at).getTime()>=cutoff);const captured=recent.filter(b=>b.payment_status==="captured");const gross=captured.reduce((s,b)=>s+Number(b.amount||0),0);const refunds=captured.reduce((s,b)=>s+Number(b.refund_amount||0),0);const net=Math.max(0,gross-refunds);const avg=captured.length?gross/captured.length:0;const refundRate=gross?refunds/gross*100:0;const paymentRate=recent.length?captured.length/recent.length*100:0;
 const restaurantMap=useMemo(()=>new Map(restaurants.map(r=>[r.id,r])),[restaurants]);
 const restaurantRows=useMemo(()=>{const m=new Map<number,{gross:number;refunds:number;paid:number;city:string;name:string}>();captured.forEach(b=>{const r=restaurantMap.get(b.restaurant_id);if(!r)return;const x=m.get(r.id)||{gross:0,refunds:0,paid:0,city:r.city,name:r.name};x.gross+=Number(b.amount||0);x.refunds+=Number(b.refund_amount||0);x.paid++;m.set(r.id,x)});return[...m.entries()].map(([id,x])=>({id,...x,net:Math.max(0,x.gross-x.refunds)})).sort((a,b)=>b.net-a.net)},[captured,restaurantMap]);
 const cityRows=useMemo(()=>{const m=new Map<string,{gross:number;refunds:number;paid:number}>();captured.forEach(b=>{const r=restaurantMap.get(b.restaurant_id);if(!r)return;const x=m.get(r.city)||{gross:0,refunds:0,paid:0};x.gross+=Number(b.amount||0);x.refunds+=Number(b.refund_amount||0);x.paid++;m.set(r.city,x)});return[...m.entries()].map(([city,x])=>({city,...x,net:Math.max(0,x.gross-x.refunds)})).sort((a,b)=>b.net-a.net)},[captured,restaurantMap]);
 const days=useMemo(()=>{const out:{label:string;gross:number;refunds:number}[]=[];for(let i=range-1;i>=0;i--){const d=new Date(Date.now()-i*86400000);const key=d.toISOString().slice(0,10);const day=captured.filter(b=>b.created_at.slice(0,10)===key);out.push({label:d.toLocaleDateString("en-IN",{day:"2-digit",month:"short"}),gross:day.reduce((s,b)=>s+Number(b.amount||0),0),refunds:day.reduce((s,b)=>s+Number(b.refund_amount||0),0)})}return out},[captured,range]);
 if(loading)return <main className="wrap">Loading revenue engine...</main>;
 const max=Math.max(1,...days.map(d=>d.gross));
 return <main className="wrap"><header><div><span className="eyebrow">DINEUP · REVENUE ENGINE · 8.3</span><h1>Revenue Control Center</h1><p>Financial view of captured payments, refunds and net collections.</p></div><div className="actions"><select value={range}onChange={e=>setRange(Number(e.target.value)as 7|30|90)}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select><button onClick={()=>router.push("/admin/growth")}>← Growth</button><button onClick={()=>router.push("/admin/dashboard")}>Admin</button></div></header>{error&&<div className="error">{error}</div>}
 <section className="cards"><Card title="Net Revenue" value={money(net)} note={`${money(gross)} gross · ${money(refunds)} refunds`}/><Card title="Gross Captured" value={money(gross)} note={`${captured.length} successful payments`}/><Card title="Refunds" value={money(refunds)} note={`${refundRate.toFixed(1)}% of gross`}/><Card title="Avg / Paid Bid" value={money(avg)} note={`${paymentRate.toFixed(1)}% bid → payment`}/></section>
 <section className="grid"><div className="panel"><h2>Revenue Trend</h2><div className="chart">{days.map((d,i)=><div className="barWrap" key={i}><div className="bar" title={`${d.label}: ${money(d.gross)}`} style={{height:`${Math.max(4,d.gross/max*100)}%`}}/><small>{d.label}</small></div>)}</div></div><div className="panel"><h2>Payment Breakdown</h2><div className="break"><Row label="Captured" value={captured.length} amount={gross}/><Row label="Other / unpaid" value={recent.length-captured.length} amount={0}/><Row label="Refunded amount" value={refunds?1:0} amount={refunds}/></div></div></section>
 <section className="grid"><div className="panel"><h2>Revenue by City</h2><div className="table">{cityRows.length?cityRows.map(x=><div className="row"key={x.city}><strong>{x.city}</strong><span>{x.paid} payments · {money(x.gross)} gross · {money(x.refunds)} refunds</span><b>{money(x.net)}</b></div>):<p>No captured revenue yet.</p>}</div></div><div className="panel"><h2>Restaurant Revenue</h2><div className="table">{restaurantRows.length?restaurantRows.slice(0,10).map((x,i)=><div className="row"key={x.id}><strong>#{i+1} {x.name}</strong><span>{x.city} · {x.paid} paid</span><b>{money(x.net)}</b></div>):<p>No captured revenue yet.</p>}</div></div></section>
 <section className="panel"><h2>Recent Financial Transactions</h2><div className="txn"><div className="tx th"><span>Bid</span><span>Restaurant</span><span>Payment</span><span>Amount</span><span>Refund</span><span>Net</span><span>Date</span></div>{recent.slice(0,50).map(b=>{const r=restaurantMap.get(b.restaurant_id);const amount=Number(b.amount||0),refund=Number(b.refund_amount||0);return <div className="tx"key={b.id}><span>#{b.id}</span><span>{r?.name||`Restaurant #${b.restaurant_id}`}</span><span><em className={b.payment_status==="captured"?"ok":"pending"}>{b.payment_status}</em></span><span>{b.payment_status==="captured"?money(amount):"—"}</span><span>{refund?money(refund):"—"}</span><span>{b.payment_status==="captured"?money(Math.max(0,amount-refund)):"—"}</span><span>{new Date(b.created_at).toLocaleDateString("en-IN")}</span></div>})}{!recent.length&&<div className="empty">No transactions in this period.</div>}</div></section><footer>Phase 8.3 · Revenue intelligence · Read-only analytics</footer><style jsx>{css}</style></main>}
function Card({title,value,note}:{title:string;value:string;note:string}){return <div className="card"><span>{title}</span><strong>{value}</strong><small>{note}</small></div>};function Row({label,value,amount}:{label:string;value:number;amount:number}){return <div className="row"><strong>{label}</strong><span>{value.toLocaleString("en-IN")} records</span><b>{amount?money(amount):"—"}</b></div>}
const css=`.wrap{min-height:100vh;background:#f6f7f9;padding:44px;max-width:1500px;margin:auto;font-family:Arial,sans-serif;color:#111}.eyebrow{font-size:12px;font-weight:700;letter-spacing:.14em;color:#666}header{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;margin-bottom:25px}h1{font-size:38px;margin:8px 0}header p{color:#666;margin:0}.actions{display:flex;gap:9px}.actions select,.actions button{padding:11px 14px;border:1px solid #ddd;border-radius:9px;background:#fff;font-weight:600}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:15px;margin-bottom:15px}.card,.panel{background:#fff;border:1px solid #e7e7e7;border-radius:16px;padding:21px;box-shadow:0 3px 15px rgba(0,0,0,.04)}.card span{font-size:13px;color:#666}.card strong{display:block;font-size:29px;margin:9px 0 5px}.card small{color:#888}.grid{display:grid;grid-template-columns:1.5fr 1fr;gap:15px;margin-bottom:15px}.panel h2{font-size:18px;margin:0 0 18px}.chart{height:220px;display:flex;align-items:end;gap:5px;border-bottom:1px solid #ddd;overflow:hidden}.barWrap{height:100%;flex:1;display:flex;flex-direction:column;justify-content:flex-end;align-items:center;gap:5px;min-width:7px}.bar{width:75%;min-height:3px;background:#111;border-radius:4px 4px 0 0}.barWrap small{font-size:9px;color:#888;white-space:nowrap;transform:rotate(-45deg);transform-origin:top right}.table,.break,.txn{display:flex;flex-direction:column}.row{display:grid;grid-template-columns:1fr 1.5fr .7fr;gap:12px;padding:14px 0;border-bottom:1px solid #eee;align-items:center}.row:last-child{border-bottom:0}.row span{color:#666;font-size:12px}.row b{text-align:right}.tx{display:grid;grid-template-columns:.5fr 1.4fr 1fr .8fr .8fr .8fr .8fr;gap:10px;align-items:center;padding:12px 5px;border-bottom:1px solid #eee;min-width:950px;font-size:12px}.txn{overflow:auto}.th{font-size:10px;text-transform:uppercase;color:#777;font-weight:700}.ok,.pending{font-style:normal;padding:4px 7px;border-radius:20px;background:#f1f1f1}.pending{opacity:.65}.error{padding:12px;background:#fff0f0;border:1px solid #f0cccc;border-radius:9px;margin-bottom:15px}.empty{padding:30px;text-align:center;color:#888}footer{text-align:center;color:#888;font-size:12px;padding:12px}@media(max-width:900px){.wrap{padding:22px}header{flex-direction:column;align-items:stretch}.cards,.grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.cards,.grid{grid-template-columns:1fr}}`;