"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { createClient } from "../../../../lib/supabase/client";

type Reservation={id:number;reservation_number:string;restaurant_id:number;reservation_date:string;reservation_time:string;party_size:number;status:string;customer_name:string;customer_phone:string|null;special_request:string|null;created_at:string};
const labels:Record<string,string>={pending:"Pending",confirmed:"Confirmed",rejected:"Rejected",cancelled:"Cancelled",completed:"Completed",no_show:"No show"};

export default function RestaurantReservations(){
 const supabase=createClient(),router=useRouter();
 const [restaurant,setRestaurant]=useState<any>(null),[rows,setRows]=useState<Reservation[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState<number|null>(null);
 const load=useCallback(async()=>{
  setLoading(true);setError("");
  try{
   const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/restaurant/login");return}
   const {data:r,error:re}=await supabase.from("restaurants").select("id,name,city").eq("owner_id",user.id).eq("is_active",true).limit(1).maybeSingle();if(re)throw re;if(!r)throw new Error("No active restaurant is linked to this account.");
   setRestaurant({...r,id:Number(r.id)});
   const {data,error}=await supabase.from("restaurant_reservations").select("id,reservation_number,restaurant_id,reservation_date,reservation_time,party_size,status,customer_name,customer_phone,special_request,created_at").eq("restaurant_id",r.id).order("reservation_date",{ascending:true}).order("reservation_time",{ascending:true}).limit(100);if(error)throw error;
   setRows((data||[]).map((x:any)=>({...x,id:Number(x.id),restaurant_id:Number(x.restaurant_id),party_size:Number(x.party_size)})));
  }catch(e:any){setError(e?.message||"Unable to load reservations.")}
  finally{setLoading(false)}
 },[router,supabase]);
 useEffect(()=>{void load()},[load]);
 async function update(id:number,status:string){
  setBusy(id);setError("");setMessage("");
  try{const {error}=await supabase.from("restaurant_reservations").update({status}).eq("id",id);if(error)throw error;setMessage("Reservation updated.");await load()}catch(e:any){setError(e?.message||"Unable to update reservation.")}finally{setBusy(null)}
 }
 const fmtDate=(v:string)=>new Date(v+"T00:00:00").toLocaleDateString("en-IN",{weekday:"short",day:"2-digit",month:"short"});
 const fmtTime=(v:string)=>{const [h,m]=v.slice(0,5).split(":").map(Number);return new Date(2000,0,1,h,m).toLocaleTimeString("en-IN",{hour:"numeric",minute:"2-digit"})};
 if(loading)return <main className="page"><div className="loading">Loading reservations…</div><style jsx>{css}</style></main>;
 return <main className="page"><style jsx>{css}</style><header><Link href="/restaurant/dashboard" className="brand">Dine<span>Up</span></Link><div><Link href="/restaurant/dashboard/orders" className="secondary">Orders</Link></div></header><div className="shell"><div className="heading"><div><small>RESTAURANT RESERVATIONS</small><h1>Table bookings</h1><p>{restaurant?.name} · Manage incoming table reservations.</p></div><Link href="/restaurant/dashboard" className="secondary">← Dashboard</Link></div>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert success">{message}</div>}<div className="cards">{!rows.length?<section className="empty"><h2>No reservations yet</h2><p>New DineUp table bookings will appear here.</p></section>:rows.map(r=><article className="card" key={r.id}><div className="top"><div><span>{r.reservation_number}</span><h2>{r.customer_name}</h2><small>{fmtDate(r.reservation_date)} · {fmtTime(r.reservation_time)} · {r.party_size} guests</small></div><b className={"status "+r.status}>{labels[r.status]||r.status}</b></div>{r.customer_phone&&<div className="detail">Phone: {r.customer_phone}</div>}{r.special_request&&<div className="detail">Request: {r.special_request}</div>}<div className="actions">{r.status==="confirmed"&&<><button onClick={()=>void update(r.id,"completed")} disabled={busy===r.id}>Mark completed</button><button className="danger" onClick={()=>void update(r.id,"no_show")} disabled={busy===r.id}>No show</button></>}{r.status==="pending"&&<><button onClick={()=>void update(r.id,"confirmed")} disabled={busy===r.id}>Confirm</button><button className="danger" onClick={()=>void update(r.id,"rejected")} disabled={busy===r.id}>Reject</button></>}{r.status==="confirmed"&&<button className="danger" onClick={()=>void update(r.id,"cancelled")} disabled={busy===r.id}>Cancel</button>}</div></article>)}</div></div></main>
}
const css=`*{box-sizing:border-box}.page{min-height:100vh;background:#f6f7f9;color:#171717;font-family:Arial,sans-serif}.page header{height:72px;border-bottom:1px solid #e6e7eb;background:#fff;display:flex;align-items:center;justify-content:space-between;padding:0 6vw}.brand{font-size:27px;font-weight:800;color:#111;text-decoration:none}.brand span{color:#ed650c}.secondary{border:1px solid #ddd;background:#fff;color:#222;text-decoration:none;border-radius:10px;padding:10px 14px;font-size:11px;font-weight:800}.shell{max-width:1120px;margin:0 auto;padding:42px 22px 70px}.heading{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;margin-bottom:24px}.heading small{font-size:11px;font-weight:900;letter-spacing:.14em;color:#777}.heading h1{font-size:40px;margin:8px 0}.heading p{font-size:13px;color:#777}.cards{display:grid;gap:12px}.card{background:#fff;border:1px solid #e5e5e5;border-radius:16px;padding:18px}.top{display:flex;justify-content:space-between;gap:15px}.top span{font-size:9px;letter-spacing:.1em;color:#888;font-weight:900}.top h2{font-size:18px;margin:5px 0}.top small{font-size:11px;color:#777}.status{padding:6px 9px;border-radius:999px;font-size:9px;text-transform:uppercase;height:max-content}.status.confirmed{background:#edf9f1;color:#1b6d39}.status.pending{background:#fff7e6;color:#8a5a00}.status.rejected,.status.cancelled,.status.no_show{background:#fff0f0;color:#a42323}.status.completed{background:#eee;color:#555}.detail{margin-top:10px;padding:9px 10px;background:#f7f7f7;border-radius:8px;font-size:11px;color:#555}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.actions button{border:1px solid #ddd;background:#fff;border-radius:9px;padding:9px 12px;font-size:10px;font-weight:900;cursor:pointer}.actions button:first-child{background:#111;color:#fff;border-color:#111}.actions .danger{background:#fff4f4;color:#a42323;border-color:#efcccc}.actions button:disabled{opacity:.5}.alert{padding:11px;border-radius:9px;margin-bottom:12px;font-size:11px}.error{background:#fff0f0;color:#a42323}.success{background:#effaf2;color:#176b35}.empty{background:#fff;border:1px dashed #ddd;border-radius:16px;padding:50px;text-align:center}.empty p{color:#777;font-size:12px}.loading{min-height:80vh;display:grid;place-items:center;color:#777;font-weight:700}@media(max-width:650px){.page header{padding:0 18px}.shell{padding:30px 14px}.heading{align-items:flex-start;flex-direction:column}}`;
