"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "../../../lib/supabase/client";

type Restaurant={id:number;name:string;city:string;category:string;is_active:boolean|null;is_claimed:boolean|null;created_at:string|null};
type Application={id:number;restaurant_name:string;city:string;category:string;status:string;created_at:string};
type Event={restaurant_id:number;event_type:string;created_at:string};
const supabase=createClient();
const money=(n:number)=>`₹${Math.round(n).toLocaleString("en-IN")}`;

export default function AcquisitionPage(){
 const router=useRouter();const[restaurants,setRestaurants]=useState<Restaurant[]>([]);const[apps,setApps]=useState<Application[]>([]);const[events,setEvents]=useState<Event[]>([]);const[range,setRange]=useState<7|30|90>(30);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/admin/login");return}const{data:admin}=await supabase.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle();if(!admin){router.replace("/admin/login");return}const[r,a,e]=await Promise.all([supabase.from("restaurants").select("id,name,city,category,is_active,is_claimed,created_at"),supabase.from("restaurant_applications").select("id,restaurant_name,city,category,status,created_at").order("created_at",{ascending:false}),supabase.from("restaurant_events").select("restaurant_id,event_type,created_at").order("created_at",{ascending:false})]);const err=r.error||a.error||e.error;if(err)setError(err.message);setRestaurants((r.data||[])as Restaurant[]);setApps((a.data||[])as Application[]);setEvents((e.data||[])as Event[]);setLoading(false)})()},[router]);
 const cutoff=Date.now()-range*86400000;const recentApps=apps.filter(a=>new Date(a.created_at).getTime()>=cutoff);const recentRestaurants=restaurants.filter(r=>r.created_at&&new Date(r.created_at).getTime()>=cutoff);const recentEvents=events.filter(e=>new Date(e.created_at).getTime()>=cutoff);const approved=recentApps.filter(a=>a.status==="approved").length;const claimed=recentRestaurants.filter(r=>r.is_claimed===true).length;const active=recentRestaurants.filter(r=>r.is_active!==false).length;
 const cityRows=useMemo(()=>{const m=new Map<string,{apps:number;approved:number;restaurants:number;claimed:number;actions:number}>();recentApps.forEach(a=>{const x=m.get(a.city)||{apps:0,approved:0,restaurants:0,claimed:0,actions:0};x.apps++;if(a.status==="approved")x.approved++;m.set(a.city,x)});recentRestaurants.forEach(r=>{const x=m.get(r.city)||{apps:0,approved:0,restaurants:0,claimed:0,actions:0};x.restaurants++;if(r.is_claimed)x.claimed++;m.set(r.city,x)});recentEvents.forEach(e=>{const r=restaurants.find(x=>x.id===e.restaurant_id);if(!r)return;const x=m.get(r.city)||{apps:0,approved:0,restaurants:0,claimed:0,actions:0};if(["call","whatsapp","directions","menu","website"].includes(e.event_type))x.actions++;m.set(r.city,x)});return[...m.entries()].map(([city,x])=>({city,...x,approvalRate:x.apps?x.approved/x.apps*100:0})).sort((a,b)=>b.approved-a.approved||b.apps-a.apps)},[recentApps,recentRestaurants,recentEvents,restaurants]);
 const eventRows=useMemo(()=>{const m=new Map<string,number>();recentEvents.forEach(e=>m.set(e.event_type,(m.get(e.event_type)||0)+1));return[...m.entries()].sort((a,b)=>b[1]-a[1])},[recentEvents]);
 if(loading)return <main className="wrap">Loading acquisition engine...</main>;
 return <main className="wrap"><header><div><span className="eyebrow">DINEUP · ACQUISITION ENGINE · 8.4</span><h1>Acquisition Control Center</h1><p>Track restaurant acquisition, city expansion and marketplace engagement.</p></div><div className="actions"><select value={range}onChange={e=>setRange(Number(e.target.value)as 7|30|90)}><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select><button onClick={()=>router.push("/admin/growth")}>← Growth</button><button onClick={()=>router.push("/admin/dashboard")}>Admin</button></div></header>{error&&<div className="error">{error}</div>}
 <section className="cards"><Card t="Applications" v={recentApps.length} n={`${range}-day inbound`}/><Card t="Approved" v={approved} n={`${recentApps.length?((approved/recentApps.length)*100).toFixed(1):"0.0"}% approval rate`}/><Card t="New Restaurants" v={recentRestaurants.length} n={`${active} active`}/><Card t="New Claims" v={claimed} n="Claimed after acquisition"/></section>
 <section className="funnel"><Box t="Applications" v={recentApps.length}/><i>→</i><Box t="Approved" v={approved}/><i>→</i><Box t="Restaurants" v={recentRestaurants.length}/><i>→</i><Box t="Claimed" v={claimed}/></section>
 <section className="grid"><div className="panel"><h2>Acquisition by City</h2><div className="table">{cityRows.map(x=><div className="row"key={x.city}><strong>{x.city}</strong><span>{x.apps} applications · {x.restaurants} new restaurants · {x.claimed} claimed</span><b>{x.approvalRate.toFixed(1)}%</b></div>)}{!cityRows.length&&<p>No acquisition data yet.</p>}</div></div><div className="panel"><h2>Marketplace Sources</h2><p className="muted">Current event tracking shows where marketplace engagement happens. UTM/source attribution is the next tracking layer.</p><div className="table">{eventRows.map(([k,v])=><div className="row"key={k}><strong>{k.replaceAll("_"," ")}</strong><span>events</span><b>{v.toLocaleString("en-IN")}</b></div>)}{!eventRows.length&&<p>No events yet.</p>}</div></div></section>
 <section className="panel"><h2>Acquisition Playbook Signals</h2><div className="signals"><Signal t="City expansion" d="Compare application volume and approval rate city-by-city before opening the next market."/><Signal t="Restaurant supply" d="Monitor new restaurants versus claims to identify where onboarding needs attention."/><Signal t="Engagement" d="Use customer action events to see whether newly acquired restaurants receive marketplace activity."/><Signal t="Campaign attribution" d="Add UTM parameters to marketing links in the next tracking layer so acquisition can be tied to campaigns."/></div></section><footer>Phase 8.4 · Acquisition intelligence · Read-only analytics</footer><style jsx>{css}</style></main>}
function Card({t,v,n}:{t:string;v:number;n:string}){return <div className="card"><span>{t}</span><strong>{v.toLocaleString("en-IN")}</strong><small>{n}</small></div>};function Box({t,v}:{t:string;v:number}){return <div><small>{t}</small><strong>{v.toLocaleString("en-IN")}</strong></div>};function Signal({t,d}:{t:string;d:string}){return <div className="signal"><strong>{t}</strong><p>{d}</p></div>}
const css=`.wrap{min-height:100vh;background:#f6f7f9;padding:44px;max-width:1500px;margin:auto;font-family:Arial,sans-serif;color:#111}.eyebrow{font-size:12px;font-weight:700;letter-spacing:.14em;color:#666}header{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;margin-bottom:25px}h1{font-size:38px;margin:8px 0}header p{color:#666;margin:0}.actions{display:flex;gap:9px}.actions select,.actions button{padding:11px 14px;border:1px solid #ddd;border-radius:9px;background:#fff;font-weight:600}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:15px;margin-bottom:15px}.card,.panel{background:#fff;border:1px solid #e7e7e7;border-radius:16px;padding:21px;box-shadow:0 3px 15px rgba(0,0,0,.04)}.card span{font-size:13px;color:#666}.card strong{display:block;font-size:29px;margin:9px 0 5px}.card small,.muted{color:#888}.funnel{display:grid;grid-template-columns:1fr auto 1fr auto 1fr auto 1fr;gap:10px;align-items:center;background:#fff;border:1px solid #e7e7e7;border-radius:16px;padding:20px;margin-bottom:15px}.funnel div{border:1px solid #eee;border-radius:11px;padding:15px}.funnel small{display:block;color:#777;font-size:10px;text-transform:uppercase}.funnel strong{font-size:25px}.funnel i{font-style:normal;color:#999}.grid{display:grid;grid-template-columns:1.3fr 1fr;gap:15px;margin-bottom:15px}.panel{margin-bottom:15px}.panel h2{font-size:18px;margin:0 0 15px}.table{display:flex;flex-direction:column}.row{display:grid;grid-template-columns:1fr 1.7fr .6fr;gap:12px;align-items:center;padding:14px 0;border-bottom:1px solid #eee}.row:last-child{border-bottom:0}.row span{font-size:12px;color:#666}.row b{text-align:right}.signals{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.signal{border:1px solid #eee;border-radius:12px;padding:15px}.signal p{color:#666;font-size:13px;line-height:1.5;margin-bottom:0}.error{padding:12px;background:#fff0f0;border:1px solid #f0cccc;border-radius:9px;margin-bottom:15px}footer{text-align:center;color:#888;font-size:12px;padding:12px}@media(max-width:900px){.wrap{padding:22px}header{flex-direction:column;align-items:stretch}.cards,.grid,.signals{grid-template-columns:1fr 1fr}.funnel{grid-template-columns:1fr}.funnel i{display:none}}@media(max-width:600px){.cards,.grid,.signals{grid-template-columns:1fr}}`;