"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { createClient } from "../../lib/supabase/client";
export default function AccountPage(){
 const router=useRouter(),supabase=createClient();const[user,setUser]=useState<any>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/login");return}setUser(user);setLoading(false)})()},[router]);
 async function signOut(){await supabase.auth.signOut();router.replace("/");router.refresh()}
 if(loading)return <main className="page"><div className="loading">Loading your account...</div><style jsx>{css}</style></main>;
 const name=user?.user_metadata?.full_name||"DineUp diner";
 return <main className="page"><header><Link href="/" className="brand"><span>D</span><b>DineUp</b></Link><button onClick={signOut}>Sign out</button></header><section className="hero"><small>YOUR DINEUP ACCOUNT</small><h1>Welcome, <em>{name.split(" ")[0]}.</em></h1><p>Keep your favourite restaurants and dining discoveries in one place.</p></section><section className="grid"><div className="panel"><i>♡</i><h2>Your favourites</h2><p>Save restaurants you want to revisit. Favourite restaurants will appear here.</p><button className="disabled" disabled>Coming next</button></div><div className="panel"><i>◷</i><h2>Recently viewed</h2><p>Keep track of restaurants you have discovered on DineUp.</p><Link href="/" className="action">Discover restaurants →</Link></div><div className="panel wide"><i>✦</i><h2>Account details</h2><div className="details"><div><small>Name</small><b>{name}</b></div><div><small>Email</small><b>{user.email}</b></div></div></div></section><style jsx>{css}</style></main>
}
const css=`*{box-sizing:border-box}.page{min-height:100vh;background:#f7f5f0;color:#171717;padding:28px max(18px,calc((100% - 1080px)/2));font-family:Arial,sans-serif}.page header{display:flex;justify-content:space-between;align-items:center}.brand{display:flex;align-items:center;gap:10px;text-decoration:none;color:#171717}.brand span{width:38px;height:38px;border-radius:11px;background:#171717;color:#ed650c;display:grid;place-items:center;font-weight:900}.brand b{font-size:21px}.page header button{border:1px solid #ddd7ce;background:#fff;border-radius:9px;padding:10px 14px;font-size:11px;font-weight:800;cursor:pointer}.hero{padding:75px 0 35px}.hero>small{font-size:9px;letter-spacing:.17em;font-weight:900;color:#8a8177}.hero h1{font-size:58px;line-height:.95;letter-spacing:-.06em;margin:10px 0}.hero h1 em{font-family:Georgia,serif;color:#d86118;font-weight:400}.hero p{color:#777;font-size:14px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.panel{background:#fff;border:1px solid #e4dfd7;border-radius:18px;padding:24px;box-shadow:0 8px 28px rgba(45,30,15,.05)}.panel.wide{grid-column:1/-1}.panel i{font-style:normal;font-size:26px;color:#ed650c}.panel h2{font-size:21px;margin:12px 0 8px}.panel p{font-size:12px;line-height:1.6;color:#777;min-height:38px}.action,.disabled{display:inline-flex;margin-top:10px;border:0;border-radius:9px;background:#171717;color:#fff;text-decoration:none;padding:11px 14px;font-size:11px;font-weight:800}.disabled{opacity:.45;cursor:not-allowed}.details{display:grid;grid-template-columns:1fr 1fr;gap:15px;margin-top:17px}.details div{background:#f7f5f0;border-radius:10px;padding:13px}.details small,.details b{display:block}.details small{font-size:9px;color:#999;text-transform:uppercase;letter-spacing:.1em}.details b{font-size:12px;margin-top:5px}.loading{min-height:80vh;display:grid;place-items:center;color:#777;font-weight:700}@media(max-width:650px){.hero{padding:50px 0 28px}.hero h1{font-size:44px}.grid{grid-template-columns:1fr}.panel.wide{grid-column:auto}.details{grid-template-columns:1fr}}`;
