"use client";
import { FormEvent,useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { createClient } from "../../lib/supabase/client";
import { trackMarketingEvent } from "../../lib/marketing-attribution";
export default function CustomerLoginPage(){
 const router=useRouter(),supabase=createClient();const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[loading,setLoading]=useState(false),[message,setMessage]=useState("");
 async function submit(e:FormEvent){e.preventDefault();setMessage("");if(!email.trim()||!password){setMessage("Please enter your email and password.");return}setLoading(true);void trackMarketingEvent("customer_login_started");const{data,error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error){console.error("CUSTOMER LOGIN ERROR:",error);if(error.code==="email_not_confirmed"){setMessage("Please confirm your email address first. Check your inbox for the verification email.");}else if(error.code==="invalid_credentials"){setMessage("Email or password is incorrect.");}else{setMessage(error.message||"Unable to sign in. Please try again.");}setLoading(false);return}if(!data.user){setMessage("Unable to create login session. Please try again.");setLoading(false);return}router.replace("/account");router.refresh()}
 return <main className="auth"><Link href="/" className="brand"><span>D</span><b>DineUp</b></Link><div className="card"><small>DINEUP ACCOUNT</small><h1>Welcome back.</h1><p>Sign in to save restaurants and keep your dining discoveries in one place.</p>{message&&<div className="msg">{message}</div>}<form onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Your password" autoComplete="current-password"/></label><button disabled={loading}>{loading?"Signing in...":"Sign in →"}</button></form><div className="bottom">New to DineUp? <Link href="/signup">Create account</Link></div><Link href="/" className="back">← Back to restaurants</Link></div><style jsx>{css}</style></main>
}
const css=`*{box-sizing:border-box}.auth{min-height:100vh;background:radial-gradient(circle at 90% 10%,rgba(237,101,12,.12),transparent 28%),#f5f2ec;padding:30px 18px;font-family:Arial,sans-serif}.brand{display:flex;align-items:center;gap:10px;text-decoration:none;color:#171717;max-width:1060px;margin:auto}.brand span{width:38px;height:38px;border-radius:11px;background:#171717;color:#ed650c;display:grid;place-items:center;font-weight:900}.brand b{font-size:21px}.card{width:min(100%,460px);margin:75px auto 0;background:#fff;border:1px solid #e3ded6;border-radius:22px;padding:34px;box-shadow:0 25px 70px rgba(40,25,10,.1)}.card>small{font-size:9px;letter-spacing:.17em;font-weight:900;color:#8a8177}.card h1{font-size:40px;letter-spacing:-.055em;margin:10px 0 8px}.card>p{font-size:13px;line-height:1.6;color:#777;margin:0 0 24px}.msg{padding:11px;border-radius:9px;background:#fff1f1;border:1px solid #efcccc;color:#9b3030;font-size:11px;margin-bottom:14px}.card form{display:grid;gap:15px}.card label{display:grid;gap:6px;font-size:10px;font-weight:800;color:#555;text-transform:uppercase;letter-spacing:.06em}.card input{height:46px;border:1px solid #ddd8d0;border-radius:9px;padding:0 12px;font-size:13px;outline:0}.card input:focus{border-color:#ed650c}.card button{height:46px;border:0;border-radius:9px;background:#171717;color:#fff;font-weight:800;cursor:pointer}.card button:disabled{opacity:.55}.bottom{text-align:center;font-size:11px;color:#777;margin-top:22px}.bottom a{color:#d86118;font-weight:800;text-decoration:none}.back{display:block;text-align:center;color:#777;text-decoration:none;font-size:11px;margin-top:20px}`;
