"use client";
import { FormEvent,useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { createClient } from "../../lib/supabase/client";
import { trackMarketingEvent } from "../../lib/marketing-attribution";
export default function CustomerSignupPage(){
 const router=useRouter(),supabase=createClient();const[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[loading,setLoading]=useState(false),[message,setMessage]=useState(""),[success,setSuccess]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setMessage("");if(!name.trim()||!email.trim()||!password){setMessage("Please complete all required fields.");return}if(password.length<8){setMessage("Password must be at least 8 characters.");return}if(password!==confirm){setMessage("Passwords do not match.");return}setLoading(true);void trackMarketingEvent("customer_signup_started");const{data,error}=await supabase.auth.signUp({email:email.trim().toLowerCase(),password,options:{data:{full_name:name.trim()}}});if(error){setMessage(error.message);setLoading(false);return}if(data.session){router.replace("/account");router.refresh();return}setSuccess(true);setLoading(false)}
 return <main className="auth"><Link href="/" className="brand"><span>D</span><b>DineUp</b></Link><div className="card"><small>JOIN DINEUP</small><h1>Create your account.</h1><p>Save restaurants you love and make discovering your next meal easier.</p>{success?<div className="success"><strong>Account created.</strong><p>Check your email if confirmation is required, then sign in to continue.</p><Link href="/login" className="primary">Continue to sign in →</Link></div>:<>{message&&<div className="msg">{message}</div>}<form onSubmit={submit}><label>Your name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" autoComplete="name"/></label><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 8 characters" autoComplete="new-password"/></label><label>Confirm password<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repeat password" autoComplete="new-password"/></label><button disabled={loading}>{loading?"Creating account...":"Create account →"}</button></form></>}<div className="bottom">Already have an account? <Link href="/login">Sign in</Link></div><Link href="/" className="back">← Back to restaurants</Link></div><style jsx>{css}</style></main>
}
const css=`*{box-sizing:border-box}.auth{min-height:100vh;background:radial-gradient(circle at 90% 10%,rgba(237,101,12,.12),transparent 28%),#f5f2ec;padding:30px 18px;font-family:Arial,sans-serif}.brand{display:flex;align-items:center;gap:10px;text-decoration:none;color:#171717;max-width:1060px;margin:auto}.brand span{width:38px;height:38px;border-radius:11px;background:#171717;color:#ed650c;display:grid;place-items:center;font-weight:900}.brand b{font-size:21px}.card{width:min(100%,460px);margin:55px auto 0;background:#fff;border:1px solid #e3ded6;border-radius:22px;padding:34px;box-shadow:0 25px 70px rgba(40,25,10,.1)}.card>small{font-size:9px;letter-spacing:.17em;font-weight:900;color:#8a8177}.card h1{font-size:38px;letter-spacing:-.055em;margin:10px 0 8px}.card>p{font-size:13px;line-height:1.6;color:#777;margin:0 0 24px}.msg{padding:11px;border-radius:9px;background:#fff1f1;border:1px solid #efcccc;color:#9b3030;font-size:11px;margin-bottom:14px}.success{padding:15px;background:#edf9f1;border:1px solid #ccebd6;border-radius:10px;color:#247b4d;font-size:12px}.success p{color:#5e7868;line-height:1.5}.primary{display:inline-flex;margin-top:8px;padding:11px 14px;border-radius:9px;background:#171717;color:#fff;text-decoration:none;font-weight:800;font-size:11px}.card form{display:grid;gap:13px}.card label{display:grid;gap:6px;font-size:10px;font-weight:800;color:#555;text-transform:uppercase;letter-spacing:.06em}.card input{height:44px;border:1px solid #ddd8d0;border-radius:9px;padding:0 12px;font-size:13px;outline:0}.card input:focus{border-color:#ed650c}.card button{height:46px;border:0;border-radius:9px;background:#171717;color:#fff;font-weight:800;cursor:pointer}.card button:disabled{opacity:.55}.bottom{text-align:center;font-size:11px;color:#777;margin-top:21px}.bottom a{color:#d86118;font-weight:800;text-decoration:none}.back{display:block;text-align:center;color:#777;text-decoration:none;font-size:11px;margin-top:20px}`;
