"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "../../../../lib/supabase/client";

type Lead={id:number;restaurant_name:string;contact_name:string|null;phone:string|null;city:string|null;status:string;next_follow_up_at:string|null;source:string|null;created_at:string};
type Referral={id:number;code:string;owner_type:string;owner_name:string;active:boolean;created_at:string};
type Step={restaurant_id:number;step:string;status:string;completed_at:string|null};
const sb=createClient();
const steps=["application","approved","profile","media","menu","payment","live"];
export default function GrowthAutomation(){
 const router=useRouter(); const[leads,setLeads]=useState<Lead[]>([]); const[refs,setRefs]=useState<Referral[]>([]); const[onboard,setOnboard]=useState<Step[]>([]); const[loading,setLoading]=useState(true); const[error,setError]=useState("");
 useEffect(()=>{(async()=>{const{data:{user}}=await sb.auth.getUser();if(!user){router.replace('/admin/login');return}const{data:a}=await sb.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();if(!a){router.replace('/admin/login');return}await load()})()},[]);
 async function load(){setLoading(true);const[l,r,o]=await Promise.all([sb.from('restaurant_leads').select('*').order('created_at',{ascending:false}).limit(100),sb.from('referral_links').select('*').order('created_at',{ascending:false}).limit(100),sb.from('restaurant_onboarding_steps').select('*').limit(500)]);if(l.error||r.error||o.error)setError(l.error?.message||r.error?.message||o.error?.message||'Unable to load growth operations');setLeads((l.data||[])as Lead[]);setRefs((r.data||[])as Referral[]);setOnboard((o.data||[])as Step[]);setLoading(false)}
 async function updateLead(id:number,status:string){await sb.from('restaurant_leads').update({status,updated_at:new Date().toISOString()}).eq('id',id);await load()}
 async function createReferral(){const owner=prompt('Creator / partner name');if(!owner)return;const type=prompt('Type: creator, restaurant, partner, internal','creator')||'creator';const code=(owner.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,30)+'-'+Math.random().toString(36).slice(2,6)).slice(0,40);const{error}=await sb.from('referral_links').insert({code,owner_type:type,owner_name:owner,target_path:'/marketplace'});if(error)setError(error.message);else await load()}
 const counts=leads.reduce((m,l)=>(m[l.status]=(m[l.status]||0)+1,m),{} as Record<string,number>);const activeOnboard=new Set(onboard.map(x=>x.restaurant_id)).size;const completed=onboard.filter(x=>x.status==='completed').length;
 if(loading)return <main className="wrap">Loading growth operations...</main>;
 return <main className="wrap"><header><div><span>DINEUP · PHASE 8.7</span><h1>Growth Operations</h1><p>Restaurant acquisition, follow-ups, referrals and onboarding control center.</p></div><div className="actions"><button onClick={()=>router.push('/admin/acquisition')}>Acquisition</button><button onClick={()=>router.push('/admin/campaigns')}>Campaign ROI</button><button onClick={()=>router.push('/admin/dashboard')}>Admin</button></div></header>{error&&<div className="error">{error}</div>}
 <section className="cards"><Card t="Total Leads" v={leads.length}/><Card t="New" v={counts.new||0}/><Card t="Follow-ups" v={(counts.contacted||0)+(counts.qualified||0)+(counts.onboarding||0)}/><Card t="Referral Links" v={refs.length}/></section>
 <section className="panel"><div className="head"><div><span>8.7.1</span><h2>Restaurant Acquisition CRM</h2></div><div className="statusline">New {counts.new||0} · Qualified {counts.qualified||0} · Onboarding {counts.onboarding||0} · Won {counts.won||0}</div></div><div className="table"><div className="row th"><span>RESTAURANT</span><span>CITY</span><span>SOURCE</span><span>STATUS</span><span>FOLLOW-UP</span></div>{leads.map(l=><div className="row" key={l.id}><strong>{l.restaurant_name}<small>{l.contact_name||l.phone||''}</small></strong><span>{l.city||'—'}</span><span>{l.source||'manual'}</span><select value={l.status} onChange={e=>updateLead(l.id,e.target.value)}><option>new</option><option>contacted</option><option>qualified</option><option>onboarding</option><option>won</option><option>lost</option></select><span>{l.next_follow_up_at?new Date(l.next_follow_up_at).toLocaleDateString('en-IN'):'—'}</span></div>)}{!leads.length&&<p className="empty">No leads yet. Add restaurant prospects here as acquisition starts.</p>}</div></section>
 <section className="panel"><div className="head"><div><span>8.7.4 · 8.7.5</span><h2>Referral & Creator Links</h2></div><button onClick={createReferral}>+ Create Link</button></div><div className="refs">{refs.map(r=><div className="ref" key={r.id}><b>{r.owner_name}</b><small>{r.owner_type} · {r.active?'active':'inactive'}</small><code>{r.code}</code><span>Use: /marketplace?ref={r.code}</span></div>)}{!refs.length&&<p className="empty">No referral links created yet.</p>}</div></section>
 <section className="panel"><div className="head"><div><span>8.7.6</span><h2>Restaurant Onboarding Funnel</h2></div><span>{activeOnboard} restaurants · {completed} completed steps</span></div><div className="funnel">{steps.map(s=>{const a=onboard.filter(x=>x.step===s&&x.status==='completed').length;return <div className="fstep" key={s}><b>{a}</b><span>{s}</span></div>})}</div></section>
 <section className="panel"><div className="head"><div><span>8.7.3 · 8.7.7</span><h2>Messaging & Reporting</h2></div></div><div className="tiles"><Tile t="WhatsApp" d="Templates and message logs are ready for provider integration."/><Tile t="Email" d="Welcome/follow-up templates are stored and auditable."/><Tile t="Follow-up Queue" d="Lead statuses provide the operational callback queue."/><Tile t="Growth Reports" d="Acquisition + Campaign ROI dashboards provide the reporting layer."/></div></section><footer>Phase 8.7 · Growth Operations · Admin only</footer><style jsx>{css}</style></main>;
}
function Card({t,v}:{t:string;v:number}){return <div className="card"><span>{t}</span><b>{v.toLocaleString('en-IN')}</b></div>}
function Tile({t,d}:{t:string;d:string}){return <div className="tile"><b>{t}</b><p>{d}</p></div>}
const css=`.wrap{min-height:100vh;background:#f6f5f2;color:#161616;padding:40px;max-width:1500px;margin:auto;font-family:Inter,Arial,sans-serif}.wrap header{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;margin-bottom:25px}.wrap header>div:first-child span,.head>div span{font-size:10px;font-weight:800;letter-spacing:.16em;color:#9a8060}.wrap h1{font-size:44px;margin:8px 0}.wrap header p{color:#666}.actions{display:flex;gap:8px}.actions button,.head button{border:1px solid #ddd;background:#fff;border-radius:9px;padding:10px 13px;font-weight:700;cursor:pointer}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:15px}.card,.panel{background:#fff;border:1px solid #e5e1da;border-radius:16px;box-shadow:0 3px 16px rgba(20,15,10,.04)}.card{padding:21px}.card span{display:block;color:#777;font-size:12px}.card b{display:block;font-size:29px;margin-top:9px}.panel{margin-bottom:15px;overflow:hidden}.head{padding:21px 24px;border-bottom:1px solid #eeeae3;display:flex;justify-content:space-between;align-items:center;gap:15px}.head h2{margin:6px 0 0;font-size:19px}.statusline,.head>span{font-size:11px;color:#777}.table{overflow:auto}.row{display:grid;grid-template-columns:2fr 1fr 1fr 1.1fr 1fr;gap:12px;align-items:center;padding:14px 24px;border-bottom:1px solid #f0ede8;min-width:800px;font-size:12px}.row small{display:block;color:#999;margin-top:4px}.th{font-size:9px;color:#999;font-weight:800;letter-spacing:.12em;background:#faf9f7}.row select{border:1px solid #ddd;border-radius:7px;padding:7px;background:#fff;font-size:11px}.empty{padding:35px 20px;text-align:center;color:#999}.refs{padding:20px 24px;display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.ref,.tile{border:1px solid #eeeae3;border-radius:12px;padding:15px}.ref b,.ref small,.ref code,.ref span{display:block}.ref small{color:#999;margin:5px 0 10px}.ref code{background:#f5f2ec;padding:7px;border-radius:7px;font-size:11px}.ref span{font-size:10px;color:#777;margin-top:8px;word-break:break-all}.funnel{padding:25px;display:grid;grid-template-columns:repeat(7,1fr);gap:10px}.fstep{text-align:center;padding:17px 8px;background:#faf9f7;border-radius:10px}.fstep b{display:block;font-size:24px}.fstep span{display:block;font-size:10px;color:#777;margin-top:5px;text-transform:capitalize}.tiles{padding:20px 24px;display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.tile p{font-size:11px;line-height:1.5;color:#777}.error{padding:12px;background:#fff0ef;border:1px solid #eccfcc;border-radius:9px;margin-bottom:15px;color:#a0443c;font-size:12px}footer{text-align:center;color:#aaa;font-size:10px;margin-top:25px}@media(max-width:900px){.wrap{padding:22px}.cards,.refs,.tiles{grid-template-columns:1fr 1fr}.wrap header{flex-direction:column;align-items:stretch}.funnel{grid-template-columns:repeat(4,1fr)}}@media(max-width:600px){.cards,.refs,.tiles{grid-template-columns:1fr}.funnel{grid-template-columns:1fr 1fr}}`;
