"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "../../../../lib/supabase/client";

type Restaurant={id:number;name:string;city:string;category:string;current_bid:number|null;is_active:boolean|null;is_claimed:boolean|null};
type Event={restaurant_id:number;event_type:string;created_at:string};
type Bid={restaurant_id:number;amount:number|string;payment_status:string;refund_amount:number|string|null;created_at:string};
const supabase=createClient();
const money=(n:number)=>`₹${Math.round(n).toLocaleString("en-IN")}`;
const actions=["call","whatsapp","directions","menu","website"];

export default function RestaurantGrowth(){
 const router=useRouter(); const [restaurants,setRestaurants]=useState<Restaurant[]>([]); const [events,setEvents]=useState<Event[]>([]); const [bids,setBids]=useState<Bid[]>([]); const [range,setRange]=useState<7|30|90>(30); const [search,setSearch]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/admin/login");return} const {data:admin}=await supabase.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle();if(!admin){router.replace("/admin/login");return} const [r,e,b]=await Promise.all([supabase.from("restaurants").select("id,name,city,category,current_bid,is_active,is_claimed"),supabase.from("restaurant_events").select("restaurant_id,event_type,created_at").order("created_at",{ascending:false}),supabase.from("bids").select("restaurant_id,amount,payment_status,refund_amount,created_at").order("created_at",{ascending:false})]);const err=r.error||e.error||b.error;if(err)setError(err.message);setRestaurants((r.data||[]) as Restaurant[]);setEvents((e.data||[]) as Event[]);setBids((b.data||[]) as Bid[]);setLoading(false)})()},[router]);
 const cutoff=Date.now()-range*86400000; const recentEvents=events.filter(x=>new Date(x.created_at).getTime()>=cutoff); const recentBids=bids.filter(x=>new Date(x.created_at).getTime()>=cutoff);
 const rows=useMemo(()=>restaurants.map(r=>{const ev=recentEvents.filter(e=>e.restaurant_id===r.id);const views=ev.filter(e=>e.event_type==="profile_view").length;const customerActions=ev.filter(e=>actions.includes(e.event_type)).length;const rb=recentBids.filter(b=>b.restaurant_id===r.id);const paid=rb.filter(b=>b.payment_status==="captured");const revenue=paid.reduce((s,b)=>s+Number(b.amount||0),0);return {...r,views,customerActions,bids:rb.length,paid:paid.length,revenue,actionRate:views?(customerActions/views)*100:0,paymentRate:rb.length?(paid.length/rb.length)*100:0}}).filter(r=>{const q=search.trim().toLowerCase();return !q||[r.name,r.city,r.category].some(v=>v.toLowerCase().includes(q))}).sort((a,b)=>b.revenue-a.revenue||b.views-a.views),[restaurants,recentEvents,recentBids,search]);
 const totals=useMemo(()=>({views:rows.reduce((s,r)=>s+r.views,0),actions:rows.reduce((s,r)=>s+r.customerActions,0),bids:rows.reduce((s,r)=>s+r.bids,0),paid:rows.reduce((s,r)=>s+r.paid,0),revenue:rows.reduce((s,r)=>s+r.revenue,0)}),[rows]);
 if(loading)return <main className="wrap">Loading restaurant growth...</main>;
 return <main className="wrap"><header><div><span>GROWTH ENGINE · 8.2</span><h1>Restaurant Growth</h1><p>Track each restaurant from visibility to customer action, bid and payment.</p></div><div className="actions"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search restaurant..."/><select value={range} onChange={e=>setRange(Number(e.target.value) as 7|30|90)}><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select><button onClick={()=>router.push("/admin/growth")}>← Growth</button></div></header>{error&&<div className="error">{error}</div>}
 <section className="cards"><Card t="Profile Views" v={totals.views}/><Card t="Customer Actions" v={totals.actions}/><Card t="Bids" v={totals.bids}/><Card t="Paid Bids" v={totals.paid}/><Card t="Revenue" v={money(totals.revenue)}/></section>
 <section className="funnel"><div><small>PROFILE VIEWS</small><strong>{totals.views.toLocaleString("en-IN")}</strong></div><i>→</i><div><small>CUSTOMER ACTIONS</small><strong>{totals.actions.toLocaleString("en-IN")}</strong></div><i>→</i><div><small>BIDS</small><strong>{totals.bids.toLocaleString("en-IN")}</strong></div><i>→</i><div><small>PAID</small><strong>{totals.paid.toLocaleString("en-IN")}</strong></div></section>
 <section className="panel"><div className="panelHead"><div><h2>Restaurant Performance</h2><p>Window: last {range} days</p></div></div><div className="table"><div className="tr th"><span>Restaurant</span><span>Views</span><span>Actions</span><span>Bids</span><span>Paid</span><span>Revenue</span><span>Action rate</span></div>{rows.map(r=><div className="tr" key={r.id}><span><b>{r.name}</b><small>{r.city} · {r.category}{r.is_claimed?" · Claimed":""}</small></span><span>{r.views}</span><span>{r.customerActions}</span><span>{r.bids}</span><span>{r.paid}</span><span>{money(r.revenue)}</span><span>{r.actionRate.toFixed(1)}%</span></div>)}{!rows.length&&<div className="empty">No restaurant activity found.</div>}</div></section>
 <section className="insights"><div className="panel"><h2>Conversion checks</h2><p>Views → actions: <b>{totals.views?(totals.actions/totals.views*100).toFixed(1):"0.0"}%</b></p><p>Bids → paid: <b>{totals.bids?(totals.paid/totals.bids*100).toFixed(1):"0.0"}%</b></p><p>Paid revenue per paid bid: <b>{totals.paid?money(totals.revenue/totals.paid):money(0)}</b></p></div><div className="panel"><h2>Operational signals</h2><p>Restaurants with views but no customer action: <b>{rows.filter(r=>r.views>0&&r.customerActions===0).length}</b></p><p>Restaurants with bids but no payment: <b>{rows.filter(r=>r.bids>0&&r.paid===0).length}</b></p><p>Active restaurants: <b>{restaurants.filter(r=>r.is_active!==false).length}</b></p></div></section><footer>Phase 8.2 · Restaurant-level growth intelligence</footer><style jsx>{css}</style></main>
}
function Card({t,v}:{t:string;v:number|string}){return <div className="card"><span>{t}</span><strong>{typeof v==="number"?v.toLocaleString("en-IN"):v}</strong></div>}
const css=`.wrap{min-height:100vh;background:#f6f7f9;padding:42px;max-width:1500px;margin:auto;font-family:Arial,sans-serif;color:#111}header{display:flex;justify-content:space-between;gap:20px;align-items:flex-end;margin-bottom:25px}header>div:first-child>span{font-size:12px;font-weight:700;letter-spacing:.14em;color:#666}h1{font-size:38px;margin:8px 0}header p{color:#666;margin:0}.actions{display:flex;gap:8px}.actions input,.actions select,.actions button{padding:11px 13px;border:1px solid #ddd;border-radius:9px;background:#fff}.cards{display:grid;grid-template-columns:repeat(5,1fr);gap:14px;margin-bottom:15px}.card,.panel{background:#fff;border:1px solid #e7e7e7;border-radius:15px;padding:20px}.card span{font-size:13px;color:#666}.card strong{display:block;font-size:27px;margin-top:8px}.funnel{display:grid;grid-template-columns:1fr auto 1fr auto 1fr auto 1fr;gap:10px;align-items:center;background:#fff;border:1px solid #e7e7e7;border-radius:15px;padding:20px;margin-bottom:15px}.funnel div{border:1px solid #eee;border-radius:11px;padding:15px}.funnel small{display:block;color:#777;font-size:10px;letter-spacing:.1em}.funnel strong{font-size:25px}.funnel i{font-style:normal;color:#999}.panel{margin-bottom:15px}.panelHead{margin-bottom:12px}.panel h2{font-size:18px;margin:0 0 5px}.panel p{color:#666;margin:5px 0}.table{overflow:auto}.tr{display:grid;grid-template-columns:2fr .7fr .8fr .6fr .6fr .9fr .8fr;gap:12px;align-items:center;padding:14px 5px;border-bottom:1px solid #eee;min-width:900px}.tr small{display:block;color:#888;font-size:11px;margin-top:3px}.th{font-size:11px;color:#777;text-transform:uppercase;font-weight:700}.insights{display:grid;grid-template-columns:1fr 1fr;gap:15px}.empty{text-align:center;color:#888;padding:30px}footer{text-align:center;color:#888;font-size:12px;padding:12px}.error{padding:12px;background:#fff0f0;border:1px solid #f0cccc;border-radius:9px;margin-bottom:15px}@media(max-width:900px){.wrap{padding:22px}header{flex-direction:column;align-items:stretch}.cards{grid-template-columns:repeat(2,1fr)}.funnel{grid-template-columns:1fr}.funnel i{display:none}.insights{grid-template-columns:1fr}}`;
