-- DineUp 10.0.8.7: restaurant promo offers
create table if not exists public.restaurant_offers (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  code text not null,
  title text not null,
  description text,
  discount_type text not null check (discount_type in ('percent','fixed')),
  discount_value numeric(12,2) not null check (discount_value > 0),
  min_order_amount numeric(12,2) not null default 0 check (min_order_amount >= 0),
  max_discount_amount numeric(12,2) check (max_discount_amount is null or max_discount_amount > 0),
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (restaurant_id, code),
  check (ends_at is null or ends_at > starts_at),
  check (discount_type <> 'percent' or discount_value <= 100)
);

create index if not exists restaurant_offers_active_idx
  on public.restaurant_offers (restaurant_id, is_active, starts_at, ends_at);

alter table public.restaurant_offers enable row level security;

drop policy if exists "restaurant offers public read" on public.restaurant_offers;
create policy "restaurant offers public read"
on public.restaurant_offers for select to anon, authenticated
using (is_active and starts_at <= now() and (ends_at is null or ends_at > now()));

drop policy if exists "restaurant owners manage offers" on public.restaurant_offers;
create policy "restaurant owners manage offers"
on public.restaurant_offers for all to authenticated
using (exists (select 1 from public.restaurants r where r.id = restaurant_offers.restaurant_id and r.owner_id = auth.uid()))
with check (exists (select 1 from public.restaurants r where r.id = restaurant_offers.restaurant_id and r.owner_id = auth.uid()));

revoke all on public.restaurant_offers from anon, authenticated;
grant select on public.restaurant_offers to anon, authenticated;
grant insert, update, delete on public.restaurant_offers to authenticated;

create or replace function public.create_order_from_cart(
  p_restaurant_id bigint,
  p_fulfillment_type text,
  p_customer_note text default null,
  p_offer_code text default null
)
returns public.orders
language plpgsql security invoker set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_cart_id bigint;
  v_order public.orders;
  v_subtotal numeric(12,2) := 0;
  v_discount numeric(12,2) := 0;
  v_offer public.restaurant_offers;
  v_code text := nullif(upper(trim(p_offer_code)), '');
begin
  if v_user_id is null then raise exception 'AUTH_REQUIRED'; end if;
  if p_fulfillment_type not in ('pickup','dine_in','delivery') then raise exception 'INVALID_FULFILLMENT_TYPE'; end if;

  select id into v_cart_id from public.customer_carts
  where user_id = v_user_id and restaurant_id = p_restaurant_id limit 1;
  if v_cart_id is null then raise exception 'CART_NOT_FOUND'; end if;

  select coalesce(sum(mi.price * ci.quantity), 0) into v_subtotal
  from public.customer_cart_items ci
  join public.restaurant_menu_items mi on mi.id = ci.menu_item_id
  where ci.cart_id = v_cart_id and mi.restaurant_id = p_restaurant_id and mi.is_available = true;
  if v_subtotal <= 0 then raise exception 'CART_EMPTY'; end if;

  if v_code is not null then
    select * into v_offer from public.restaurant_offers
    where restaurant_id = p_restaurant_id and upper(code) = v_code and is_active = true
      and starts_at <= now() and (ends_at is null or ends_at > now()) limit 1;
    if not found then raise exception 'INVALID_OFFER'; end if;
    if v_subtotal < v_offer.min_order_amount then raise exception 'OFFER_MIN_ORDER_NOT_MET'; end if;

    if v_offer.discount_type = 'percent' then
      v_discount := round(v_subtotal * v_offer.discount_value / 100, 2);
    else
      v_discount := v_offer.discount_value;
    end if;
    if v_offer.max_discount_amount is not null then v_discount := least(v_discount, v_offer.max_discount_amount); end if;
    v_discount := least(v_discount, v_subtotal);
  end if;

  insert into public.orders (
    order_number, customer_id, restaurant_id, status, payment_status,
    fulfillment_type, subtotal, discount_amount, delivery_fee, total_amount, customer_note
  )
  values (
    'DU-' || to_char(now(), 'YYYYMMDD') || '-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 8)),
    v_user_id, p_restaurant_id, 'pending', 'pending',
    p_fulfillment_type, v_subtotal, v_discount, 0, v_subtotal - v_discount, nullif(trim(p_customer_note), '')
  )
  returning * into v_order;

  insert into public.order_items (order_id, menu_item_id, item_name, unit_price, quantity, line_total)
  select v_order.id, mi.id, mi.name, mi.price, ci.quantity, round(mi.price * ci.quantity, 2)
  from public.customer_cart_items ci
  join public.restaurant_menu_items mi on mi.id = ci.menu_item_id
  where ci.cart_id = v_cart_id and mi.restaurant_id = p_restaurant_id and mi.is_available = true;

  delete from public.customer_carts where id = v_cart_id;
  return v_order;
end;
$$;

revoke execute on function public.create_order_from_cart(bigint,text,text) from public, anon, authenticated;
revoke execute on function public.create_order_from_cart(bigint,text,text,text) from public, anon;
grant execute on function public.create_order_from_cart(bigint,text,text,text) to authenticated;
