alter table public.bids
  add column if not exists refund_status text not null default 'none',
  add column if not exists refund_amount numeric(12,2),
  add column if not exists razorpay_refund_id text,
  add column if not exists refund_reason text,
  add column if not exists refunded_at timestamptz;

alter table public.bids
  drop constraint if exists bids_refund_status_check;

alter table public.bids
  add constraint bids_refund_status_check
  check (refund_status in ('none','pending','processed','failed'));

create unique index if not exists bids_razorpay_refund_id_uidx
  on public.bids (razorpay_refund_id)
  where razorpay_refund_id is not null;

create table if not exists public.bid_refunds (
  id bigint generated by default as identity primary key,
  bid_id bigint not null references public.bids(id) on delete cascade,
  razorpay_refund_id text not null unique,
  razorpay_payment_id text not null,
  amount numeric(12,2) not null check (amount > 0),
  status text not null check (status in ('pending','processed','failed')),
  reason text,
  created_at timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists bid_refunds_bid_id_idx on public.bid_refunds(bid_id);
create index if not exists bid_refunds_payment_id_idx on public.bid_refunds(razorpay_payment_id);

alter table public.bid_refunds enable row level security;

create policy if not exists "Admins can view bid refunds"
on public.bid_refunds
for select
to authenticated
using (exists (select 1 from public.admin_users a where a.user_id = auth.uid()));

revoke all on public.bid_refunds from anon, public;
revoke all on public.bid_refunds from authenticated;
grant select on public.bid_refunds to authenticated;

create or replace function public.record_bid_refund_from_webhook(
  p_bid_id bigint,
  p_razorpay_refund_id text,
  p_refund_status text,
  p_refund_amount numeric,
  p_refund_reason text default null,
  p_razorpay_payment_id text default null
)
returns public.bids
language plpgsql
security definer
set search_path = public
as $$
declare
  v_bid public.bids;
begin
  if p_refund_status not in ('pending','processed','failed') then
    raise exception 'Invalid refund status';
  end if;

  if p_razorpay_refund_id is null or length(trim(p_razorpay_refund_id)) = 0 then
    raise exception 'Refund ID is required';
  end if;

  select * into v_bid from public.bids where id = p_bid_id for update;
  if v_bid.id is null then raise exception 'Bid not found'; end if;

  insert into public.bid_refunds (
    bid_id, razorpay_refund_id, razorpay_payment_id, amount, status, reason, processed_at
  )
  values (
    p_bid_id,
    p_razorpay_refund_id,
    coalesce(nullif(trim(p_razorpay_payment_id), ''), v_bid.razorpay_payment_id),
    p_refund_amount,
    p_refund_status,
    nullif(trim(p_refund_reason), ''),
    case when p_refund_status = 'processed' then now() else null end
  )
  on conflict (razorpay_refund_id) do update
  set status = excluded.status,
      amount = excluded.amount,
      reason = coalesce(excluded.reason, public.bid_refunds.reason),
      processed_at = case when excluded.status = 'processed' then coalesce(public.bid_refunds.processed_at, now()) else public.bid_refunds.processed_at end;

  update public.bids
  set razorpay_refund_id = p_razorpay_refund_id,
      refund_status = p_refund_status,
      refund_amount = p_refund_amount,
      refund_reason = coalesce(nullif(trim(p_refund_reason), ''), refund_reason),
      refunded_at = case when p_refund_status = 'processed' then coalesce(refunded_at, now()) else refunded_at end
  where id = p_bid_id
  returning * into v_bid;

  return v_bid;
end;
$$;

revoke all on function public.record_bid_refund_from_webhook(bigint,text,text,numeric,text,text) from public, anon, authenticated;
grant execute on function public.record_bid_refund_from_webhook(bigint,text,text,numeric,text,text) to service_role;
