create table if not exists public.customer_loyalty_points (user_id uuid primary key references auth.users(id) on delete cascade, points integer not null default 0 check(points>=0), lifetime_earned integer not null default 0 check(lifetime_earned>=0), lifetime_redeemed integer not null default 0 check(lifetime_redeemed>=0), updated_at timestamptz not null default now());
create table if not exists public.customer_loyalty_ledger (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, points integer not null check(points<>0), reason text not null, order_id bigint references public.orders(id) on delete set null, created_at timestamptz not null default now());
alter table public.customer_loyalty_points enable row level security;
alter table public.customer_loyalty_ledger enable row level security;
drop policy if exists "customer_loyalty_points_self_select" on public.customer_loyalty_points;
create policy "customer_loyalty_points_self_select" on public.customer_loyalty_points for select to authenticated using (user_id=auth.uid());
drop policy if exists "customer_loyalty_ledger_self_select" on public.customer_loyalty_ledger;
create policy "customer_loyalty_ledger_self_select" on public.customer_loyalty_ledger for select to authenticated using (user_id=auth.uid());
create index if not exists customer_loyalty_ledger_user_created_idx on public.customer_loyalty_ledger(user_id, created_at desc);
