-- 10.0.9.5 review moderation and abuse protection
create table if not exists public.restaurant_review_reports (
 id bigint generated by default as identity primary key,
 review_id bigint not null references public.restaurant_reviews(id) on delete cascade,
 reporter_id uuid not null references auth.users(id) on delete cascade,
 reason text not null check (reason in ('spam','abusive','fake','personal_information','other')),
 details text,
 status text not null default 'pending' check (status in ('pending','reviewed','dismissed')),
 created_at timestamptz not null default now(),
 reviewed_at timestamptz,
 unique(review_id, reporter_id)
);
create index if not exists restaurant_review_reports_status_idx on public.restaurant_review_reports(status, created_at desc);
alter table public.restaurant_review_reports enable row level security;
drop policy if exists "review reports customer create" on public.restaurant_review_reports;
create policy "review reports customer create" on public.restaurant_review_reports for insert to authenticated
with check ((select auth.uid())=reporter_id and exists (select 1 from public.restaurant_reviews rr where rr.id=review_id and rr.status='published'));
drop policy if exists "review reports customer read own" on public.restaurant_review_reports;
create policy "review reports customer read own" on public.restaurant_review_reports for select to authenticated
using ((select auth.uid())=reporter_id);
revoke all on public.restaurant_review_reports from anon;
grant select,insert on public.restaurant_review_reports to authenticated;