-- 10.0.9: verified restaurant reviews + trust
create table if not exists public.restaurant_reviews (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  order_id bigint not null references public.orders(id) on delete cascade,
  customer_id uuid not null references auth.users(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  title text,
  body text,
  status text not null default 'published' check (status in ('published','hidden')),
  owner_response text,
  owner_responded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint restaurant_reviews_one_per_order unique(order_id)
);
create index if not exists restaurant_reviews_restaurant_created_idx on public.restaurant_reviews(restaurant_id, created_at desc);
create index if not exists restaurant_reviews_customer_idx on public.restaurant_reviews(customer_id, created_at desc);
alter table public.restaurant_reviews enable row level security;
create policy "reviews public read published" on public.restaurant_reviews for select to anon, authenticated using (status='published');
create policy "reviews customer read own" on public.restaurant_reviews for select to authenticated using ((select auth.uid())=customer_id);
create policy "reviews customer create verified order" on public.restaurant_reviews for insert to authenticated
with check (
  (select auth.uid())=customer_id and exists (
    select 1 from public.orders o
    where o.id=order_id and o.customer_id=(select auth.uid())
      and o.restaurant_id=restaurant_id and o.status='completed' and o.payment_status='paid'
  )
);
create policy "reviews owner response" on public.restaurant_reviews for update to authenticated
using (exists (select 1 from public.restaurants r where r.id=restaurant_id and r.owner_id=(select auth.uid())))
with check (exists (select 1 from public.restaurants r where r.id=restaurant_id and r.owner_id=(select auth.uid())));
grant select on public.restaurant_reviews to anon, authenticated;
grant insert, update on public.restaurant_reviews to authenticated;