-- DineUp 10.0.8.1: order and cart foundation

create table if not exists public.restaurant_menu_items (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  name text not null,
  description text,
  price numeric(12,2) not null check (price >= 0),
  image_url text,
  category text,
  is_available boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists restaurant_menu_items_restaurant_idx on public.restaurant_menu_items(restaurant_id,is_available,sort_order);

create table if not exists public.customer_carts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id,restaurant_id)
);
create index if not exists customer_carts_user_idx on public.customer_carts(user_id);

create table if not exists public.customer_cart_items (
  id bigint generated by default as identity primary key,
  cart_id bigint not null references public.customer_carts(id) on delete cascade,
  menu_item_id bigint not null references public.restaurant_menu_items(id) on delete restrict,
  quantity integer not null default 1 check(quantity > 0 and quantity <= 99),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(cart_id,menu_item_id)
);
create index if not exists customer_cart_items_cart_idx on public.customer_cart_items(cart_id);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  customer_id uuid not null references auth.users(id) on delete restrict,
  restaurant_id bigint not null references public.restaurants(id) on delete restrict,
  status text not null default 'pending' check(status in ('pending','accepted','rejected','preparing','ready','completed','cancelled')),
  payment_status text not null default 'pending' check(payment_status in ('pending','paid','failed','refunded','partially_refunded')),
  fulfillment_type text not null default 'pickup' check(fulfillment_type in ('pickup','dine_in','delivery')),
  subtotal numeric(12,2) not null default 0 check(subtotal >= 0),
  discount_amount numeric(12,2) not null default 0 check(discount_amount >= 0),
  delivery_fee numeric(12,2) not null default 0 check(delivery_fee >= 0),
  total_amount numeric(12,2) not null default 0 check(total_amount >= 0),
  customer_note text,
  cancellation_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists orders_customer_idx on public.orders(customer_id,created_at desc);
create index if not exists orders_restaurant_idx on public.orders(restaurant_id,created_at desc);
create index if not exists orders_status_idx on public.orders(status,created_at desc);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  menu_item_id bigint references public.restaurant_menu_items(id) on delete set null,
  item_name text not null,
  unit_price numeric(12,2) not null check(unit_price >= 0),
  quantity integer not null check(quantity > 0 and quantity <= 99),
  line_total numeric(12,2) not null check(line_total >= 0),
  created_at timestamptz not null default now()
);
create index if not exists order_items_order_idx on public.order_items(order_id);

alter table public.restaurant_menu_items enable row level security;
alter table public.customer_carts enable row level security;
alter table public.customer_cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "menu items public read" on public.restaurant_menu_items;
create policy "menu items public read" on public.restaurant_menu_items for select to anon,authenticated
using(is_available=true and exists(select 1 from public.restaurants r where r.id=restaurant_menu_items.restaurant_id and r.is_active=true));
drop policy if exists "menu items owner manage" on public.restaurant_menu_items;
create policy "menu items owner manage" on public.restaurant_menu_items for all to authenticated
using(exists(select 1 from public.restaurants r where r.id=restaurant_menu_items.restaurant_id and r.owner_id=auth.uid()))
with check(exists(select 1 from public.restaurants r where r.id=restaurant_menu_items.restaurant_id and r.owner_id=auth.uid()));

drop policy if exists "carts own" on public.customer_carts;
create policy "carts own" on public.customer_carts for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

drop policy if exists "cart items own" on public.customer_cart_items;
create policy "cart items own" on public.customer_cart_items for all to authenticated
using(exists(select 1 from public.customer_carts c where c.id=customer_cart_items.cart_id and c.user_id=auth.uid()))
with check(exists(select 1 from public.customer_carts c where c.id=customer_cart_items.cart_id and c.user_id=auth.uid()));

drop policy if exists "orders customer read" on public.orders;
create policy "orders customer read" on public.orders for select to authenticated using(customer_id=auth.uid());
drop policy if exists "orders restaurant read" on public.orders;
create policy "orders restaurant read" on public.orders for select to authenticated
using(exists(select 1 from public.restaurants r where r.id=orders.restaurant_id and r.owner_id=auth.uid()));
drop policy if exists "orders customer create" on public.orders;
create policy "orders customer create" on public.orders for insert to authenticated with check(customer_id=auth.uid());
drop policy if exists "orders restaurant status update" on public.orders;
create policy "orders restaurant status update" on public.orders for update to authenticated
using(exists(select 1 from public.restaurants r where r.id=orders.restaurant_id and r.owner_id=auth.uid()))
with check(exists(select 1 from public.restaurants r where r.id=orders.restaurant_id and r.owner_id=auth.uid()));

drop policy if exists "order items participant read" on public.order_items;
create policy "order items participant read" on public.order_items for select to authenticated
using(exists(select 1 from public.orders o where o.id=order_items.order_id and (o.customer_id=auth.uid() or exists(select 1 from public.restaurants r where r.id=o.restaurant_id and r.owner_id=auth.uid()))));
drop policy if exists "order items customer create" on public.order_items;
create policy "order items customer create" on public.order_items for insert to authenticated
with check(exists(select 1 from public.orders o where o.id=order_items.order_id and o.customer_id=auth.uid()));

create or replace function public.touch_order_cart_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at=now(); return new; end;
$$;

drop trigger if exists restaurant_menu_items_updated_at on public.restaurant_menu_items;
create trigger restaurant_menu_items_updated_at before update on public.restaurant_menu_items for each row execute function public.touch_order_cart_updated_at();
drop trigger if exists customer_carts_updated_at on public.customer_carts;
create trigger customer_carts_updated_at before update on public.customer_carts for each row execute function public.touch_order_cart_updated_at();
drop trigger if exists customer_cart_items_updated_at on public.customer_cart_items;
create trigger customer_cart_items_updated_at before update on public.customer_cart_items for each row execute function public.touch_order_cart_updated_at();
drop trigger if exists orders_updated_at on public.orders;
create trigger orders_updated_at before update on public.orders for each row execute function public.touch_order_cart_updated_at();
