-- DineUp Phase 18: ordering + reservations
-- Reservation capacity is enforced atomically inside create_restaurant_reservation.

create sequence if not exists public.restaurant_reservation_number_seq;

create table if not exists public.restaurant_reservation_settings (
  restaurant_id bigint primary key references public.restaurants(id) on delete cascade,
  enabled boolean not null default true,
  slot_interval_minutes integer not null default 30 check (slot_interval_minutes in (15,30,60)),
  capacity_per_slot integer not null default 20 check (capacity_per_slot > 0 and capacity_per_slot <= 500),
  max_party_size integer not null default 20 check (max_party_size > 0 and max_party_size <= 100),
  advance_days integer not null default 30 check (advance_days between 1 and 90),
  min_notice_minutes integer not null default 60 check (min_notice_minutes between 0 and 1440),
  updated_at timestamptz not null default now()
);

create table if not exists public.restaurant_reservations (
  id bigint generated by default as identity primary key,
  reservation_number text not null unique default (
    'RES-' || to_char(current_date,'YYMMDD') || '-' ||
    lpad(nextval('public.restaurant_reservation_number_seq')::text, 6, '0')
  ),
  customer_id uuid not null references auth.users(id) on delete restrict,
  restaurant_id bigint not null references public.restaurants(id) on delete restrict,
  reservation_date date not null,
  reservation_time time not null,
  party_size integer not null check (party_size > 0 and party_size <= 100),
  status text not null default 'confirmed' check (status in ('pending','confirmed','rejected','cancelled','completed','no_show')),
  customer_name text not null,
  customer_phone text,
  special_request text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists restaurant_reservations_customer_idx
  on public.restaurant_reservations(customer_id, reservation_date desc, reservation_time desc);
create index if not exists restaurant_reservations_restaurant_slot_idx
  on public.restaurant_reservations(restaurant_id, reservation_date, reservation_time, status);
create index if not exists restaurant_reservations_status_idx
  on public.restaurant_reservations(status, reservation_date, reservation_time);

alter table public.restaurant_reservation_settings enable row level security;
alter table public.restaurant_reservations enable row level security;

drop policy if exists "reservation settings public read" on public.restaurant_reservation_settings;
create policy "reservation settings public read" on public.restaurant_reservation_settings for select to anon, authenticated
using (exists (select 1 from public.restaurants r where r.id = restaurant_reservation_settings.restaurant_id and r.is_active = true));

drop policy if exists "reservation settings owner manage" on public.restaurant_reservation_settings;
create policy "reservation settings owner manage" on public.restaurant_reservation_settings for all to authenticated
using (exists (select 1 from public.restaurants r where r.id = restaurant_reservation_settings.restaurant_id and r.owner_id = (select auth.uid())))
with check (exists (select 1 from public.restaurants r where r.id = restaurant_reservation_settings.restaurant_id and r.owner_id = (select auth.uid())));

drop policy if exists "reservations customer read" on public.restaurant_reservations;
create policy "reservations customer read" on public.restaurant_reservations for select to authenticated using ((select auth.uid()) = customer_id);

drop policy if exists "reservations customer cancel" on public.restaurant_reservations;
create policy "reservations customer cancel" on public.restaurant_reservations for update to authenticated
using ((select auth.uid()) = customer_id and status in ('pending','confirmed'))
with check ((select auth.uid()) = customer_id and status = 'cancelled');

drop policy if exists "reservations restaurant read" on public.restaurant_reservations;
create policy "reservations restaurant read" on public.restaurant_reservations for select to authenticated
using (exists (select 1 from public.restaurants r where r.id = restaurant_reservations.restaurant_id and r.owner_id = (select auth.uid())));

drop policy if exists "reservations restaurant status" on public.restaurant_reservations;
create policy "reservations restaurant status" on public.restaurant_reservations for update to authenticated
using (exists (select 1 from public.restaurants r where r.id = restaurant_reservations.restaurant_id and r.owner_id = (select auth.uid())))
with check (exists (select 1 from public.restaurants r where r.id = restaurant_reservations.restaurant_id and r.owner_id = (select auth.uid())));

create or replace function public.touch_restaurant_reservation_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists restaurant_reservation_settings_updated_at on public.restaurant_reservation_settings;
create trigger restaurant_reservation_settings_updated_at before update on public.restaurant_reservation_settings
for each row execute function public.touch_restaurant_reservation_updated_at();

drop trigger if exists restaurant_reservations_updated_at on public.restaurant_reservations;
create trigger restaurant_reservations_updated_at before update on public.restaurant_reservations
for each row execute function public.touch_restaurant_reservation_updated_at();

create or replace function public.get_restaurant_reservation_slots(p_restaurant_id bigint,p_date date)
returns table(slot_time time,remaining_capacity integer,available boolean)
language sql security definer set search_path = '' stable as $$
  with settings as (
    select coalesce(s.slot_interval_minutes,30) interval_minutes,
           coalesce(s.capacity_per_slot,20) capacity,
           coalesce(s.enabled,true) enabled
    from public.restaurants r
    left join public.restaurant_reservation_settings s on s.restaurant_id=r.id
    where r.id=p_restaurant_id and r.is_active=true limit 1
  ), slots as (
    select g::time slot_time
    from settings s, generate_series(timestamp '2000-01-01 11:00',timestamp '2000-01-01 22:00',make_interval(mins=>s.interval_minutes)) g
    where s.enabled=true
  ), booked as (
    select reservation_time,coalesce(sum(party_size),0)::integer booked
    from public.restaurant_reservations
    where restaurant_id=p_restaurant_id and reservation_date=p_date and status in ('pending','confirmed')
    group by reservation_time
  )
  select s.slot_time,greatest(0,st.capacity-coalesce(b.booked,0))::integer,
         greatest(0,st.capacity-coalesce(b.booked,0))>0
  from slots s cross join settings st left join booked b on b.reservation_time=s.slot_time
  order by s.slot_time
$$;

revoke execute on function public.get_restaurant_reservation_slots(bigint,date) from public;
grant execute on function public.get_restaurant_reservation_slots(bigint,date) to anon,authenticated;

create or replace function public.create_restaurant_reservation(
  p_restaurant_id bigint,p_date date,p_time time,p_party_size integer,
  p_customer_name text,p_customer_phone text default null,p_special_request text default null
)
returns public.restaurant_reservations
language plpgsql security definer set search_path = '' as $$
declare
  v_user_id uuid := (select auth.uid());
  v_settings public.restaurant_reservation_settings%rowtype;
  v_restaurant public.restaurants%rowtype;
  v_booked integer := 0;
  v_result public.restaurant_reservations;
begin
  if v_user_id is null then raise exception 'You must be signed in to reserve a table.'; end if;
  if p_date is null or p_time is null then raise exception 'Please choose a date and time.'; end if;
  if p_date < current_date then raise exception 'Reservation date must be today or later.'; end if;
  if p_party_size is null or p_party_size < 1 then raise exception 'Party size must be at least 1.'; end if;

  select * into v_restaurant from public.restaurants where id=p_restaurant_id and is_active=true limit 1;
  if not found then raise exception 'Restaurant is not available.'; end if;

  insert into public.restaurant_reservation_settings(restaurant_id) values(p_restaurant_id) on conflict(restaurant_id) do nothing;
  select * into v_settings from public.restaurant_reservation_settings where restaurant_id=p_restaurant_id for update;

  if not v_settings.enabled then raise exception 'Online reservations are currently unavailable for this restaurant.'; end if;
  if p_party_size > v_settings.max_party_size then raise exception 'This restaurant accepts parties up to % guests per reservation.',v_settings.max_party_size; end if;
  if p_date > current_date + v_settings.advance_days then raise exception 'Reservations can be made up to % days in advance.',v_settings.advance_days; end if;
  if p_date=current_date and ((p_date+p_time) < (current_date+localtime+make_interval(mins=>v_settings.min_notice_minutes))) then raise exception 'Please choose a later reservation time.'; end if;
  if extract(minute from p_time)::integer % v_settings.slot_interval_minutes <> 0 then raise exception 'Please choose one of the available time slots.'; end if;

  perform pg_advisory_xact_lock(hashtextextended(p_restaurant_id::text||':'||p_date::text||':'||p_time::text,0));

  select coalesce(sum(party_size),0)::integer into v_booked
  from public.restaurant_reservations
  where restaurant_id=p_restaurant_id and reservation_date=p_date and reservation_time=p_time and status in ('pending','confirmed');

  if v_booked+p_party_size > v_settings.capacity_per_slot then raise exception 'That time slot is full. Please choose another time.'; end if;

  insert into public.restaurant_reservations(customer_id,restaurant_id,reservation_date,reservation_time,party_size,status,customer_name,customer_phone,special_request)
  values(v_user_id,p_restaurant_id,p_date,p_time,p_party_size,'confirmed',left(trim(coalesce(p_customer_name,'')),120),nullif(left(trim(coalesce(p_customer_phone,'')),30),''),nullif(left(trim(coalesce(p_special_request,'')),500),''))
  returning * into v_result;
  return v_result;
end;
$$;

revoke execute on function public.create_restaurant_reservation(bigint,date,time,integer,text,text,text) from public;
grant execute on function public.create_restaurant_reservation(bigint,date,time,integer,text,text,text) to authenticated;
